FROM alpine:3.3
MAINTAINER Zachary Zhao <zachary.zxj@outlook.com>
RUN apk --no-cache add openjdk8-jre-base 
RUN apk --no-cache add \
	python \
	py-pip \
	wget
#RUN rm -rf /var/cache/*
#CMD ["/usr/bin/java" "-version"]
