{
 "title": "Zabbix监控平台",
 "description": "Zabbix监控平台",
 "tags": [ "zabbix " ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Group", "label": "Group", "query": "*" },
   { "name": "Host", "label": "Host", "query": "$Group.*" }
  ]
 },
 "panels": [
  { "title": "当前时间", "type": "grafana-clock-panel", "description": "当前时间", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "Zabbix server队列数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Zabbix server" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Zabbix queue" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Free memory" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Linux CPU空闲比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "CPU idle time" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu率百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "CPU使用率百分比" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Windows当前系统时间",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "application": { "filter": "time" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "itServiceFilter": "$Host",
     "item": { "filter": "windows时间监控" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "OK time", "property": "okTime" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Linux当前系统时间",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "application": { "filter": "OS" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Host local time" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "网卡流量图",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/Incoming.*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/Outgoing.*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "网卡流量数据",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/.*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu 使用情况",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/.*.(load)/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "磁盘剩余百分比",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/^Free disk.*.(tage)/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "磁盘当前状态",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/^Total.*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/^Used.*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "$Group" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zabbix Busy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Zabbix server" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "/Zabbix busy/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "报警告警",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 25 },
   "targets": {
    "Zabbix": {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  }
 ]
}